### ISSUE TITLE
TypeError: inference() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by ghost** [ShinYwings/HDR-Map-Reconstruction-From-a-Single-LDR-Sky-Panoramic-Image-For-Outdoor-Illumination-Estimation#2]
pred_hdr = inference(ldr_val)
               ^^^^^^^^^^^^^^^^^^
TypeError: inference() missing 1 required positional argument: 'args'

**Comment by ghost** [comment]
I constantly get this error. This is my command line argument

python inference.py --indir ./new --outdir ./name

**Comment by ShinYwings** [comment]
Just fixed it, too. Sorry for the continued error🥲. After completing the source code, I added `argparse` for ease of use, but I couldn't confirm that it works.
